spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pgdb
    username: pgmanager
    #password: 1234
    password: pgadmin1234@
  jpa:
    hibernate:
      ddl-auto: create

logging:
  level:
    root: info
  file:
    name: /home/pi/logs/workLog.log

server:
  port: 5000