spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pgdb
    username: pgmanager
    password: pgadmin1234@
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create


server:
  port: 5000